name: Manual Docker Install with Script

on:
  workflow_dispatch:

jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker install script
        run: bash install.sh
      - name: Docker install successfully
        run: echo " Docker Install !!!!!!!!!!!!!!!! "
        
      - name: Build and run NGINX
        run: |
          cat <<EOF > Dockerfile
          FROM nginx:alpine
          COPY ./index.html /usr/share/nginx/html/index.html
          EOF

          echo "<h1>Hello from NGINX in GitHub Actions</h1>" > index.html

          docker build -t my-nginx .
          docker run -d -p 8080:80 --name nginx-server my-nginx
          sleep 5
          curl -s http://localhost:8080
