name: Manual Docker Install with Script

on:
  workflow_dispatch:

jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x install.sh  # Use +x instead of 777 for security

      - name: Run Docker install script
        run: bash install.sh
